# general setting.
views: 2
seed: 3407
wandb: false
experiment_name: "emnist"
verbose: false
note: 'disentangling'
project_name: 'CVPR24'
runtimes: 1
backbone:
  type: 'cnn'
  init_method: 'xavier'
dataset:
  name: 'EdgeMnist'
  root: 'MyData'
  class_num: 10
train:
  epochs: 200
  # 64, 128, 512, 1024
  devices: [0, 1]
  batch_size: 2048
  optim: "adamw"
  num_workers: 8
  lr: 0.0005
  evaluate: 1
  use_ddp: true
  scheduler: 'consine'
  samples_num: 8
  resume: false


consistency:
  continous: True
  c_dim: 10
  in_channel: 1
  ch_mult: [1, 2, 4]
  block_size: 8
  basic_hidden_dim: 16
  latent_ch: 8
  num_res_blocks: 3
  kld_weight: 1.0
  alpha: 1.0

vspecific:
  v_dim: 10
  ch_mult: [1, 2, 4]
  block_size: 8
  basic_hidden_dim: 16
  latent_ch: 8
  num_res_blocks: 3
  best_view: 0
  kld_weight: 0.5

disent:
  hidden_size: 100
  alpha: 0.05

valid_augmentation:
  crop_size: 32

eval:
  model_path: 'model-1529.pth'

